development:
  FACEBOOK_APP_ID: 263037113842257
  FACEBOOK_SECRET: c92e4e1241aed5e33270813f1e3a066b
  TWITTER_CONSUMER_KEY: enFq5OIH6B1qx58cdsVfGA
  TWITTER_COMSUMER_SECRET: vHEZ1VNppEsUMrWaqrSgs8PMFoivttA32s0fzGbi8
production:
  FACEBOOK_APP_ID: 129745623888871
  FACEBOOK_SECRET: bc7470c3bb0a1dbdbe8d46e87fce3455
  TWITTER_CONSUMER_KEY: enFq5OIH6B1qx58cdsVfGA
  TWITTER_COMSUMER_SECRET: vHEZ1VNppEsUMrWaqrSgs8PMFoivttA32s0fzGbi8